name: todoe
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  provider: ^4.0.5+1
  sqflite: ^1.3.0
  path_provider: ^1.6.7
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Janna
      fonts:
        - asset: assets/fonts/janna.woff
        - asset: assets/fonts/janna-bold.woff
